neurovault::main { 'nvault-install':
  env_path => "/opt/nv-env",
  db_name => "neurovault",
  db_username => "neurovault",
  db_userpassword => "neurovault",
  db_existing_sql => "/home/grivera/nv-backup.sql",
  app_url => "http://nvault.infocortex.de",
  host_name => "nvault.infocortex.de",
  system_user => "grivera",
  tmp_dir => "/home/grivera/downloads",
  repo_url => "https://github.com/chrisfilo/NeuroVault.git",
  repo_branch => "master",
  neurodeb_list => "http://neuro.debian.net/lists/trusty.de-m.libre",
  neurodeb_sources => "/etc/apt/sources.list.d/neurodebian.sources.list",
  neurodeb_apt_key => "hkp://pgp.mit.edu:80 2649A5A9",
  http_server => "nginx",
  dbbackup_storage =>"dbbackup.storage.dropbox_storage",
  dbbackup_tokenpath =>"<local_tokens_filepath>",
  dbbackup_appkey =>"<dropbox_app_key>",
  dbbackup_secret =>"<dropbox_app_secret>",
  start_debug =>"true",
  private_media_root => "/opt/nv-env/image_data",
  private_media_url => "/media/images",
  private_media_existing => "/home/grivera/neurovault_testdata/image_data",
  gmail_login_str => "system-notify@infocortex.com:themailpasswd",
  freesurfer_dl_path => "ftp://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/5.3.0",
  freesurfer_src => "freesurfer-Linux-centos4_x86_64-stable-pub-v5.3.0.tar.gz",
  freesurfer_installdir => "/opt",
  freesurfer_lic_email => "burk@cbs.mpg.de",
  freesurfer_lic_id => "6204",
  freesurfer_lic_key => " *CTxMh/xk9q62", # note leading space.
  bash_config_loc => "/etc/profile.d/freesurfer.sh",
  pycortex_repo => "https://github.com/gallantlab/pycortex.git",
  pycortex_branch => "master",
  pycortex_datastore => "/opt/nv-env/pycortex_data",
  neurovault_data_repo => "https://github.com/NeuroVault/neurovault_data/trunk/",

}
